# Generated by Django 5.0 on 2023-12-29 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, unique=True, verbose_name='Декан')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Название')),
                ('departments', models.ManyToManyField(blank=True, related_name='faculty_departments', to='myapp.department', verbose_name='Кафедры')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Ta', 'Ta'), ('Tб', 'Tb'), ('Тв', 'Tc'), ('Ра', 'Ra'), ('Рб', 'Rb'), ('Рв', 'Rc')], max_length=5, verbose_name='Группа')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('code_name', models.IntegerField(unique=True, verbose_name='Кодовое название')),
                ('course', models.SmallIntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fifth')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciality_department', to='myapp.department', verbose_name='Кафедра')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_Name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('course', models.SmallIntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fifth')], verbose_name='Год учёбы')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_speciality', to='myapp.speciality', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес эл.почты')),
                ('phone_number', models.IntegerField(blank=True, verbose_name='Номер телефона')),
                ('role', models.SmallIntegerField(choices=[(1, 'Учитель'), (2, 'Декан'), (3, 'Заведующий кафедрой')], verbose_name='Роль')),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_department', to='myapp.department', verbose_name='Кафедра')),
                ('faculty', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_faculty', to='myapp.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.AddField(
            model_name='speciality',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher', verbose_name='Куратор'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='head',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_head', to='myapp.teacher', verbose_name='Декан'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_head', to='myapp.teacher', verbose_name='Заведующий кафедры'),
        ),
    ]
